const PERMISSIONS = {
  // System Admin Permissions
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',
  VIEW_HEALTH: 'VIEW_HEALTH',
  MANAGE_USERS: 'MANAGE_USERS',
  DELETE_ANY_EXPENSE: 'DELETE_ANY_EXPENSE',

  // Group Management Permissions
  CREATE_GROUP: 'CREATE_GROUP',
  UPDATE_GROUP: 'UPDATE_GROUP', // Group Admin
  DELETE_GROUP: 'DELETE_GROUP', // Group Admin
  ADD_MEMBER: 'ADD_MEMBER',     // Group Admin
  REMOVE_MEMBER: 'REMOVE_MEMBER',  // Group Admin

  // Expense/Settlement Permissions
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE', // Creator or Group Admin
  CREATE_SETTLEMENT: 'CREATE_SETTLEMENT',
  APPROVE_SETTLEMENT: 'APPROVE_SETTLEMENT' // Group Admin
};

const ROLE_PERMISSIONS = {
  guest: [
    PERMISSIONS.VIEW_HEALTH
  ],
  user: [
    PERMISSIONS.CREATE_GROUP,
    PERMISSIONS.CREATE_EXPENSE,
    PERMISSIONS.CREATE_SETTLEMENT
  ],
  admin: [ // maps to system_admin
    PERMISSIONS.VIEW_AUDIT_LOGS,
    PERMISSIONS.VIEW_HEALTH,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.DELETE_ANY_EXPENSE,
    PERMISSIONS.CREATE_GROUP,
    PERMISSIONS.UPDATE_GROUP,
    PERMISSIONS.DELETE_GROUP,
    PERMISSIONS.ADD_MEMBER,
    PERMISSIONS.REMOVE_MEMBER,
    PERMISSIONS.CREATE_EXPENSE,
    PERMISSIONS.DELETE_EXPENSE,
    PERMISSIONS.CREATE_SETTLEMENT,
    PERMISSIONS.APPROVE_SETTLEMENT
  ]
};

// Group-level permissions check helper
const isGroupAdminPermission = (permission) => {
  return [
    PERMISSIONS.UPDATE_GROUP,
    PERMISSIONS.DELETE_GROUP,
    PERMISSIONS.ADD_MEMBER,
    PERMISSIONS.REMOVE_MEMBER,
    PERMISSIONS.APPROVE_SETTLEMENT
  ].includes(permission);
};

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  isGroupAdminPermission
};
